version: "3.9"
services:
  publisher:
    build:
      context: ./publisher
    container_name: publisher
  subscriber:
    build:
      context: ./subscriber
    container_name: subscriber
    volumes:
      - ./subscriber/mqtt_log.txt:/app/mqtt_log.txt
    ports:
      - "5000:5000"

